In [1]:
import torch
if torch.cuda.is_available():
    device=torch.device('cuda')
else:
    device=torch.device('cpu')
print(device)

cuda


In [23]:
a = torch.rand(9).view(1,1,3,3)

In [24]:
a.shape

torch.Size([1, 1, 3, 3])

In [25]:
a

tensor([[[[0.1294, 0.6980, 0.0725],
          [0.1019, 0.6675, 0.4179],
          [0.6322, 0.7592, 0.9721]]]])

In [32]:
ct = torch.nn.ConvTranspose2d(
    in_channels=1,
    out_channels=1,
    kernel_size=(3,3),
    padding=0,
    stride=2,
)

In [33]:
ct.weight

Parameter containing:
tensor([[[[ 0.0448,  0.1243,  0.2389],
          [ 0.2741,  0.2558,  0.2780],
          [ 0.0034,  0.0713, -0.1770]]]], requires_grad=True)

In [34]:
ct(a)

tensor([[[[0.2202, 0.2304, 0.2766, 0.3011, 0.3844, 0.2234, 0.2317],
          [0.2498, 0.2475, 0.4416, 0.3929, 0.4283, 0.2329, 0.2345],
          [0.2194, 0.2362, 0.2481, 0.3471, 0.2693, 0.2715, 0.3014],
          [0.2423, 0.2404, 0.4256, 0.3851, 0.5145, 0.3213, 0.3305],
          [0.2430, 0.3002, 0.3837, 0.3563, 0.3226, 0.3650, 0.3726],
          [0.3876, 0.3761, 0.5982, 0.4086, 0.6919, 0.4631, 0.4846],
          [0.2165, 0.2595, 0.1050, 0.2685, 0.0833, 0.2837, 0.0423]]]],
       grad_fn=<ConvolutionBackward0>)

In [38]:
c2d = torch.nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=(3,3),
    padding=0,
    stride=1,
)

In [39]:
c2d.weight

Parameter containing:
tensor([[[[ 0.0238,  0.0812, -0.1762],
          [ 0.0274, -0.2249, -0.0848],
          [-0.0918, -0.0363, -0.2633]]]], requires_grad=True)

In [40]:
c2d(a)

tensor([[[[-0.2898]]]], grad_fn=<ConvolutionBackward0>)